# Tcl package index file, version 1.1
# This file is generated by the "pkg_mkIndex" command
# and sourced either when an application starts up or
# by a "package unknown" script.  It invokes the
# "package ifneeded" command to set up package-related
# information so that packages will be loaded automatically
# in response to "package require" commands.  When this
# script is sourced, the variable $dir must contain the
# full path name of this file's directory.

package ifneeded s4s-song    1.0 [list source [file join $dir s4s-song.tcl]]
package ifneeded s4s-print   1.0 [list source [file join $dir s4s-print.tcl]]
package ifneeded s4s-set     1.0 [list source [file join $dir s4s-set.tcl]]
package ifneeded s4s-table   1.0 [list source [file join $dir s4s-table.tcl]]
package ifneeded s4s-dialog  1.0 [list source [file join $dir s4s-dialog.tcl]]
package ifneeded s4s-toolbar 1.0 [list source [file join $dir s4s-toolbar.tcl]]
package ifneeded s4s-tkabc   1.0 [list source [file join $dir s4s-tkabc.tcl]]
package ifneeded s4s-canvas  1.0 [list source [file join $dir s4s-canvas.tcl]]
package ifneeded s4s-debug   1.0 [list source [file join $dir s4s-debug.tcl]]
package ifneeded s4s-canvas-pencil  1.0 [list source [file join $dir s4s-canvas-pencil.tcl]]

