package require s4s-song 1.0

set to_german {
	Alle-Schoepfung-staunt-und-preist.s4s-song
	Auf-den-Fluegeln-des-Windes-(Er-kommt).s4s-song
	Bis-ich-dir-gegenueber-steh-(Till-I-See-you).s4s-song
	Das-Beste.s4s-song
	Das-ist-mein-Koenig.s4s-song
	Dein-Wort-ist-ein-Licht.s4s-song
	Deine-Hand-ist-ueber-mir.s4s-song
	Deine-Herrlichkeit.s4s-song
	Der-Herr-segne-dich.s4s-song
	Die-Liebe-selbst.s4s-song
	Dir-gebuehrt-die-Ehre.s4s-song
	Du-allein-rettest-mich.s4s-song
	Du-dessen-Name-heilig-ist.s4s-song
	Du-hast-gesagt.s4s-song
	Du-siehst-die-Wunden.s4s-song
	Er-heisst-Jahwe.s4s-song
	Frei-sein.s4s-song
	Frei.s4s-song
	Gib-nicht-auf.s4s-song
	Grosser-Herrlicher-Gott.s4s-song
	Halleluja-(Agnus-Dei).s4s-song
	Handgemacht-(Es-war-gut).s4s-song
	Heilig-Heilig-das-Lamm-Gottes.s4s-song
	Herr-der-ganzen-Schoepfung.s4s-song
	Herr-du-bist-maechtig.s4s-song
	Herr-gib-uns-deinen-Frieden.s4s-song
	Herr-sprich-lauter-zu-mir.s4s-song
	Herr-wohin-sonst.s4s-song
	Herrlicher-Tag.s4s-song
	Hosanna-in-der-Hoehe.s4s-song
	Ich-darf-ehrlich-sein-vor-dir.s4s-song
	Ich-verdanke-dir-soviel.s4s-song
	Ich-weiss-dass-mein-Erloeser-lebt-(Komm-komm-du-Sohn-des-Hoechsten).s4s-song
	In-der-Heiligen-Schrift.s4s-song
	Ja-von-heute-an.s4s-song
	Je-und-je-geliebt.s4s-song
	Jesus-Herr-ich-denke-an-dein-Opfer.s4s-song
	Jesus-traegt-dich.s4s-song
	Keiner.s4s-song
	Leben-aus-der-Quelle.s4s-song
	Lobe-den-Herrn-(Ich-geb-dir-mein-Schwachsein).s4s-song
	Macht-hoch-die-Tuer.s4s-song
	Majestaet.s4s-song
	Mehr-als-genug.s4s-song
	Mein-Erloeser-lebt.s4s-song
	Meine-Zeit-steht-in-deinen-Haenden.s4s-song
	Morgenstern.s4s-song
	Mutig-komm-ich-vor-deinen-Thron-.s4s-song
	Naeher.s4s-song
	Oh-du-froehliche.s4s-song
	Schoepfer-aller-Himmel.s4s-song
	Sei-behuetet.s4s-song
	Shabbat-Schalom.s4s-song
	Siehst-du-das-Lamm.s4s-song
	So-gross-ist-der-Herr-(Ein-Koenig-voller-Pracht).s4s-song
	So-weit.s4s-song
	Stand-der-Dinge.s4s-song
	Ueber-die-Berge-und-das-Meer.s4s-song
	Unser-Gott-.s4s-song
	Vater-deine-Liebe-ist-so-unbegreeiflich-gross.s4s-song
	Vater-wir-sind-hier.s4s-song
	Von-guten-Maechten.s4s-song
	Vor-dir-(In-deinem-Licht-will-ich-leben).s4s-song
	Wege-vor-mir.s4s-song
	Wenn-Glaube-bei-uns-einzieht.s4s-song
	Wer-auf-Gott-vertraut.s4s-song
	Wer-bittet-dem-wird-gegeben.s4s-song
	Wir-erheben-dich-(Geh-uns-voraus).s4s-song
	Wir-sind-eins.s4s-song
	Wir-sind-hier-um-anzubeten.s4s-song
	Wir-sind-hier-zusammen-in-Jesu-Namen.s4s-song
	Wir-sind-hier-zusammen.s4s-song
	Wo-ich-auch-stehe.s4s-song
	Wunderbarer-Hirt.s4s-song
	Zehntausend-Gruende.s4s-song
	Andi's-Songs/Hochzeit-JanaMartin.s4s-song
	Checked/Allein-deine-Gnade-genuegt.s4s-song
	Checked/Bei-dir-bleiben-(Wir-gehen-unsere-Wege).s4s-song
	Checked/Danke.s4s-song
	Checked/Du-bist-die-Kraft-die-mir-oft-fehlt.s4s-song
	Checked/Du-bist-gut-Herr.s4s-song
	Checked/Du-tust.s4s-song
	Checked/Ewig-treuer-Gott.s4s-song
	Checked/Fuer-den-Koenig.s4s-song
	Checked/Gott-segne-dich-(Ich-wuensch-dir-Gottes-segen).s4s-song
	Checked/Halleluja!-Lobet-Gott-in-seinem-Heiligtum.s4s-song
	Checked/Halleluja-(Die-ganze-Schoepfung-jubelt-dir-zu).s4s-song
	Checked/Herr-deine-Guete-reicht-so-weit.s4s-song
	Checked/Hoeher.s4s-song
	Checked/Ich-atme-auf.s4s-song
	Checked/Komm-jetzt-ist-die-Zeit.s4s-song
	Checked/Licht-dieser-Welt.s4s-song
	Checked/Lobe-den-Herrn-meine-Seele.s4s-song
	Checked/Majestaet-herrliche-Majestaet.s4s-song
	Checked/Mein-ganzes-Leben-(Ich-gebe-dir-mein-Herz).s4s-song
	Checked/Mein-Retter-Erloeser.s4s-song
	Checked/Mighty-to-save.s4s-song
	Checked/Mittelpunkt.s4s-song
	Checked/Vater-unser.s4s-song
	Checked/Wunderbar-zeigst-du-dich.s4s-song
	Need-work/Allezeit.s4s-song
	Need-work/Dreimal-(Werd-ich-dir-folgen).s4s-song
	Need-work/Ehre.s4s-song
	Need-work/Es-ist-so-gut-wieder-vor-dir-zu-stehen.s4s-song
	Need-work/Im-Herzen-ein-Lied.s4s-song
	Need-work/Mit-aller-Kraft.s4s-song
	Need-work/My-Redeemer-Lives.s4s-song
	Need-work/Neu-geborn.s4s-song
	Need-work/Niemand-und-nichts.s4s-song
	Need-work/One-way.s4s-song
	Need-work/So-bist-nur-du.s4s-song
	Need-work/Treu-(Du-bleibst-an-meiner-Seite).s4s-song
	Need-work/Was-fuer-ein-Mensch.s4s-song
	Need-work/Wasser-des-Lebens.s4s-song
	Need-work/Wenn-ich-dich-anbete.s4s-song
	Need-work/Wir-halten-hoch-das-Kreuz.s4s-song
	Need-work/Zwischen-Himmel-und-Erde.s4s-song
	Sonstige/Jingle.s4s-song
	Thomas'-Songs/Dort-am-Kreuz.s4s-song
	Thomas'-Songs/Fokus-verloren.s4s-song
	Thomas'-Songs/Freiheit.s4s-song
	Thomas'-Songs/Jeden-Tag.s4s-song
	Thomas'-Songs/Perfektion.s4s-song
	Thomas'-Songs/Vor-deinem-Thron.s4s-song
	Thomas'-Songs/Thomas'-Band/Atem-im-Wind.s4s-song
	Thomas'-Songs/Thomas'-Band/Eingesperrt.s4s-song
	Thomas'-Songs/Thomas'-Band/Fokus-verloren.s4s-song
	Thomas'-Songs/Thomas'-Band/Sonnenaufgang-Part-I.s4s-song
	Thomas'-Songs/Thomas'-Band/Sonnenaufgang-Part-II.s4s-song
	Thomas'-Songs/Thomas'-Band/Vermaechtnis.s4s-song
	Unchecked/Alles-was-atmet.s4s-song
	Unchecked/Anker-in-der-Zeit.s4s-song
	Unchecked/Atem-Gottes.s4s-song
	Unchecked/Bahnt-einen-Weg-unserm-Gott.s4s-song
	Unchecked/Bist-zu-uns-wie-ein-Vater.s4s-song
	Unchecked/Da-wo-man-ohne-Hoffnung-lebt.s4s-song
	Unchecked/Danke-Vater-fuer-das-Leben.s4s-song
	Unchecked/Danke-Vater.s4s-song
	Unchecked/Das-was-mich-atmen-laesst.s4s-song
	Unchecked/Dein-Wort-ist-ein-Licht.s4s-song
	Unchecked/Deine-Worte.s4s-song
	Unchecked/Dennoch-(Wer-auf-Gott-vertraut).s4s-song
	Unchecked/Der-Herr-segne-dich.s4s-song
	Unchecked/Der-Himmel-erfuellt-mein-Herz.s4s-song
	Unchecked/Du-allein-bist-Koenig.s4s-song
	Unchecked/Du-bist-ein-wunderbarer-Hirt.s4s-song
	Unchecked/Du-bist-erhoben-fuer-immer-gehoert-dir-der-Thron.s4s-song
	Unchecked/Du-bist-hier.s4s-song
	Unchecked/Du-bist-mein-Zufluchtsort.s4s-song
	Unchecked/Du-bist-meine-Zuflucht-und-Staerke.s4s-song
	Unchecked/Du-bist-wuerdig.s4s-song
	Unchecked/Du-hast-Erbarmen.s4s-song
	Unchecked/Du-machst-mich-frei.s4s-song
	Unchecked/Ein-Tag-bei-dir.s4s-song
	Unchecked/Es-ist-mir-so-was-von-egal.s4s-song
	Unchecked/Etwas-in-mir.s4s-song
	Unchecked/Glaube-Hoffnung-Liebe.s4s-song
	Unchecked/Gott-hat-mir-laengst-einen-Engel-gesandt.s4s-song
	Unchecked/Gott-ist-gegenwaertig.s4s-song
	Unchecked/Grosser-Gott-wir-loben-dich.s4s-song
	Unchecked/Halleluja-(du-begeisterst-mich).s4s-song
	Unchecked/Heilig-heilig-stark-und-maechtig.s4s-song
	Unchecked/Heilig-heilig.s4s-song
	Unchecked/Herr-das-Licht-deiner-Liebe.s4s-song
	Unchecked/Herr-dein-Name-sei-erhoeht.s4s-song
	Unchecked/Herr-deine-Gnade.s4s-song
	Unchecked/Herr-hier-ist-mein-Herz.s4s-song
	Unchecked/Herr-hoer-mein-Gebet.s4s-song
	Unchecked/Herr-ich-komme-zu-dir.s4s-song
	Unchecked/Herr-ich-suche-Deine-Ruhe.s4s-song
	Unchecked/Herr-im-Glanz-deiner-Majestaet.s4s-song
	Unchecked/Herr-in-deinem-Namen.s4s-song
	Unchecked/Herr-oeffne-du-mir-die-Augen.s4s-song
	Unchecked/Herr-sei-gnaedig.s4s-song
	Unchecked/Herrlicher-Gott.s4s-song
	Unchecked/I-Have-Decided-To-Follow-Jesus.s4s-song
	Unchecked/Ich-bin-umher-gezogen.s4s-song
	Unchecked/Ich-kann-nicht-schweigen.s4s-song
	Unchecked/Immer-mehr-von-dir.s4s-song
	Unchecked/In-Christus.s4s-song
	Unchecked/In-der-Stille-angekommen.s4s-song
	Unchecked/Jesus-Christus-ist-aller-Herr.s4s-song
	Unchecked/Jesus-Dir-gehoert-all-mein-Lob.s4s-song
	Unchecked/Jesus-du-allein---Wuerdig-und-herrlich-ist-das-Lamm.s4s-song
	Unchecked/Jesus-in-my-House.s4s-song
	Unchecked/Jesus-Loves-Even-Me.s4s-song
	Unchecked/Jesus-nimm-zu.s4s-song
	Unchecked/Jesus-sei-willkommen.s4s-song
	Unchecked/Jesus-zu-dir.s4s-song
	Unchecked/Keiner-ist-wie-du.s4s-song
	Unchecked/Komm-Herr-komm.s4s-song
	Unchecked/Komm-so-wie-du-bist.s4s-song
	Unchecked/Lamm-Gottes.s4s-song
	Unchecked/Lobe-den-Herren-den-maechtigen-Koenig-der-Ehren.s4s-song
	Unchecked/Lobe-den-Herrn-meine-Seele.s4s-song
	Unchecked/Lobpreis-und-Ehre.s4s-song
	Unchecked/Lord-I-Lift-Your-Name-On-High.s4s-song
	Unchecked/Mach-weit-die-Tuer-des-Himmels.s4s-song
	Unchecked/Mein-Herz-schlaegt-fuer-dich.s4s-song
	Unchecked/Mein-Jesus-mein-Retter.s4s-song
	Unchecked/Meine-Hoffnung.s4s-song
	Unchecked/Naehme-ich-Fluegel-der-Morgenroete.s4s-song
	Unchecked/Nichts-auf-dieser-Welt---Ich-gehoere-dir.s4s-song
	Unchecked/O-Herr-giesse-Stroeme.s4s-song
	Unchecked/Oeffne-meine-Augen.s4s-song
	Unchecked/Privileg-zu-sein.s4s-song
	Unchecked/Pures-Leben.s4s-song
	Unchecked/Regier-in-mir-(Ueber-alle-Welt).s4s-song
	Unchecked/Reinige-mein-Herz.s4s-song
	Unchecked/Seid-froehlich-in-der-Hoffnung.s4s-song
	Unchecked/Starker-Gott.s4s-song
	Unchecked/Stille-vor-dir.s4s-song
	Unchecked/Tief-in-mir-brennt-ein-Feuer.s4s-song
	Unchecked/Ueber-alle-Welt.s4s-song
	Unchecked/Unser-Gott-ist-ein-maechtiger-Gott.s4s-song
	Unchecked/Vater-ich-komme-jetzt-zu-dir.s4s-song
	Unchecked/Vater-wir-kommen-vor-deinen-Thron.s4s-song
	Unchecked/Weites-Land.s4s-song
	Unchecked/Wir-sind-voll-Hoffnung.s4s-song
	Unchecked/Wir-suchen-deine-Naehe.s4s-song
	Unchecked/Wuerdig-und-herrlich-ist-das-Lamm.s4s-song
	Unchecked/Zieh-mich-hin-zu-dir.s4s-song
	Unchecked/Zwischen-dir-und-mir.s4s-song
	Unchecked/Freaksongs/Allein-du.s4s-song
	Unchecked/Freaksongs/Alles-wird-gut.s4s-song
	Unchecked/Freaksongs/Am-Boden.s4s-song
	Unchecked/Freaksongs/Das-gefaellt-mir.s4s-song
	Unchecked/Freaksongs/Deine-Stimme.s4s-song
	Unchecked/Freaksongs/Du-bist-das-Leben.s4s-song
	Unchecked/Freaksongs/Du-bist.s4s-song
	Unchecked/Freaksongs/Du-Bleibst.s4s-song
	Unchecked/Freaksongs/Du-weisst-ganz-genau.s4s-song
	Unchecked/Freaksongs/Ehrfurcht-bleibt.s4s-song
	Unchecked/Freaksongs/Erwecke-mich.s4s-song
	Unchecked/Freaksongs/Es-gibt-so-Tage.s4s-song
	Unchecked/Freaksongs/Ewigkeit.s4s-song
	Unchecked/Freaksongs/Fluegel.s4s-song
	Unchecked/Freaksongs/Frei.s4s-song
	Unchecked/Freaksongs/Fuer-immer-und-Ewig.s4s-song
	Unchecked/Freaksongs/Geliebter-Vater.s4s-song
	Unchecked/Freaksongs/Glory.s4s-song
	Unchecked/Freaksongs/Heiliger-Geist.s4s-song
	Unchecked/Freaksongs/Herz.s4s-song
	Unchecked/Freaksongs/Ich-Glaube.s4s-song
	Unchecked/Freaksongs/Ich-sehne-mich-nach-dir.s4s-song
	Unchecked/Freaksongs/Immer-da.s4s-song
	Unchecked/Freaksongs/Jesus-bitte-veraendere-Mich.s4s-song
	Unchecked/Freaksongs/Jesus-wir-erheben-deinen-Nam.s4s-song
	Unchecked/Freaksongs/Jesusmovement.s4s-song
	Unchecked/Freaksongs/Kapitulation.s4s-song
	Unchecked/Freaksongs/Meine-Haende-sind-leer.s4s-song
	Unchecked/Freaksongs/More-of-you.s4s-song
	Unchecked/Freaksongs/Never-be-hungry-again.s4s-song
	Unchecked/Freaksongs/Oeffne-das-Tor.s4s-song
	Unchecked/Freaksongs/Ohne-dich.s4s-song
	Unchecked/Freaksongs/Ohne-Jesus.s4s-song
	Unchecked/Freaksongs/Schau-mich-an.s4s-song
	Unchecked/Freaksongs/Sei-mein-Pilot.s4s-song
	Unchecked/Freaksongs/Sei-willkommen.s4s-song
	Unchecked/Freaksongs/Something-like-Psalm-23.s4s-song
	Unchecked/Freaksongs/Sprachlos.s4s-song
	Unchecked/Freaksongs/Vater.s4s-song
	Unchecked/Freaksongs/Western-Tussy.s4s-song
	Unchecked/Freaksongs/Zeichen-seiner-Hand.s4s-song
	Unchecked/Freaksongs/Zu-Jesus.s4s-song
	_Todo/Gross-und-wunderbar.s4s-song
	_Todo/Ich-bin-bei-euch-alle-Tage.s4s-song
	_Todo/Ich-tauch-ein.s4s-song
	_Todo/Nur-du-allein-Herr.s4s-song
	_Todo/Segen-fuer-deinen-neuen-Weg.s4s-song
	_Todo/Unseren-Augen-verborgen.s4s-song
}

set to_english {
	Unchecked/Leaning-On-The-Everlasting-Arms.s4s-song
	My-Glorious.s4s-song
	Running-into-you.s4s-song
	Say-Say.s4s-song
	Wonderful-Maker.s4s-song
}

proc change-language {files from to} {
	foreach song $files {
		set song [file join $::env(S4S_DATA_DIR) song $song]
		foreach sec [s4s-song::sections $song] {
			set output [list]
			s4s-song::foreach-sec-line $song $sec cmd rest {
				if {$cmd eq $from} {
					lappend output "$to $rest"
				} else {
					lappend output "$cmd $rest"
				}
			}
			s4s-song::set-sec $song $sec [join $output "\n"]
		}
		s4s-song::set-prop $song language $to
	}
}

change-language $to_english de eng
